version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando Docker..."
      - apt-get update -y && apt-get install -y docker.io

  pre_build:
    commands:
      - echo "Logando no ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Instalando dependências..."
      - npm install -g prisma
      - npm install
      - npx prisma generate
      - npx prisma migrate deploy

  build:
    commands:
      - echo "Buildando imagem Docker..."
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo "Enviando imagem para ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest

cache:
  paths:
    - node_modules/**/*
    - prisma/.env