version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando Docker..."
      - sudo dnf install -y docker  # Instala o Docker via dnf
      - sudo systemctl start docker
      - sudo usermod -a -G docker $USER  # Adiciona o usuário ao grupo docker
      - npm install -g @nestjs/cli

  pre_build:
    commands:
      - echo "Autenticando no ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Instalando dependências..."
      - npm install --legacy-peer-deps
      - npm run build

  build:
    commands:
      - echo "Construindo imagem Docker..."
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo "Enviando imagem para ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest

cache:
  paths:
    - node_modules/**/*
    - dist/**/*