version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependências do sistema..."
      - apt-get update -y
      - apt-get install -y docker.io
      - npm install -g @nestjs/cli  # Instalação única do Nest CLI

  pre_build:
    commands:
      - echo "Autenticando no Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo "Instalando dependências do projeto..."
      - npm install --legacy-peer-deps

      - echo "Buildando aplicação NestJS..."
      - npm run build

  build:
    commands:
      - echo "Construindo imagem Docker..."
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo "Enviando imagem para ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest

cache:
  paths:
    - node_modules/**/*
    - dist/**/*
    - .npm/**/*