export enum GatewayProvider {
  SAFE2PAY = 'SAFE2PAY',
  MERCADO_PAGO = 'MERCADO_PAGO',
  INTER_BANK = 'INTER_BANK',
  PAGSTAR = 'PAGSTAR',
  OPENPIX = 'OPENPIX',
  SUITPAY = 'SUITPAY',
  SAQPAY = 'SAQPAY',
  PAGGUEIO = 'PAGGUEIO',
  STARPAY = 'STARPAY',
  CIELO = 'CIELO',
  FIREBANKING = 'FIREBANKING',
  CELCOIN = 'CELCOIN',
}
