export enum NotificationsPreferencesEnum {
  'MAIL_NEW_INDICATION' = 'MAIL_NEW_INDICATION',
  'MAIL_INDICATION_SALE' = 'MAIL_INDICATION_SALE',
  'MAIL_NEW_SALE_CONFIRM' = 'MAIL_NEW_SALE_CONFIRM',
  'MOBILE_APPROVED_SALES' = 'MOBILE_APPROVED_SALES',
  'MOBILE_GENERATED_PIX_AND_BANK_SLIP' = 'MOBILE_GENERATED_PIX_AND_BANK_SLIP',
}
